#!/usr/bin/env python
"""Shortcut to build PDF by Sphinx.

This uses docker container.
"""

import os
import subprocess
from pathlib import Path

root = Path(__file__).parent.parent

cmd = [
    "docker",
    "run",
    "--rm",
    "-v",
    f"{root}:/docs",
]

if "GITHUB_ACTIONS" not in os.environ:
    cmd.append("-it")

cmd += [
    "sphinxdoc/sphinx-latexpdf",
    "sphinx-build",
    "-M",
    "latexpdf",
    "/docs/content",
    "/docs/build",
]

subprocess.run(cmd)
